version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-car-service
    environment:
      MYSQL_ROOT_PASSWORD: K8r7!xLp9@Vd
      MYSQL_DATABASE: carservicedb
      MYSQL_USER: carserviceuser
      MYSQL_PASSWORD: carservicepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - carservice-network

volumes:
  db_data:

networks:
  carservice-network: